- name: Play level variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Access URL in Task1
      ansible.builtin.debug:
        msg: URL in Task1 = {{URL}}

    - name: Access URL in Task2
      ansible.builtin.debug:
        msg: URL in Task2 = {{URL}}

# Declare variable in playlevel, then all the tasks can access that variable

- name: Play level variables 2
  hosts: all
  vars:
    URL1: play.example.com
    URL2: check.example.com
  tasks:
    - name: Access URL in Task1
      ansible.builtin.debug:
        msg: URL in Task1 = {{URL1}}

    - name: Access URL in Task2
      ansible.builtin.debug:
        msg: URL in Task2 = {{URL2}}

# Declaring variable from file

- name: Demo on File level variables
  hosts: all
  vars_files:
    - 03-sample-vars.yml
  tasks:
    - name: Access URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
