- name: Setup repos for RabbitMQ
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install Erlang
  ansible.builtin.yum:
    name:
      - https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
      - rabbitmq-server
    state: present

- name: Start RabbitMQ service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Setup Roboshop user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    tags: administrator
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
